on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
      - develop

name: "Build & Release"

jobs:
  build:
    name: Build & Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get Flutter version from pubspec
        run: |
          set -e

          brew install yq
          _flutterVersion=$( yq read pubspec.yaml environment.flutter )
          echo "FLUTTER_VERSION=${_flutterVersion}" >> $GITHUB_ENV

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: "v1.0.${{ github.run_number }}"

      - name: Flutter pub get
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release --split-per-abi

      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*"
          prerelease: false
          tag: "v1.0.${{ github.run_number }}" # Use the extracted version
          token: ${{ secrets.TOKEN }}
