on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
      - develop

name: "Build & Release"

jobs:
  build:
    name: Build & Release
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set tag as environment variable
        run: echo "TAG=$GITHUB_REF" >> $GITHUB_ENV

      - name: Extract version from tag
        id: extract_version
        run: echo "::set-output name=version::$(echo $TAG | sed -n 's/refs\/tags\/v//p')"

      - name: Update pubspec.yaml with version
        run: |
          sed -i.bak "s/version:.*/version: \${{ github.run_number }}/" pubspec.yaml
        shell: bash

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.8.0' # Update to your desired Flutter version

      - name: Flutter pub get
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release --split-per-abi

      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*"
          prerelease: false
          tag: "v1.0.${{ github.run_number}}" # Use the extracted version
          token: ${{ secrets.TOKEN }}
